### ISSUE TITLE
Arc Height and Width

### ISSUE THREAD

**Issue by yeedle** [Yeedle/2048#2]
Every tile has an arc height and an arc width, which is very similar to the border-radius property of CSS. In the [original implementation](https://gabrielecirulli.github.io/2048/style/main.css) a border radius of 3px is used. Should we keep it as close to the original as possible, or should we make it more sleek looking by rounding the edges? What do you think, @modicohen?

**Comment by modicohen** [comment]
I'm not sure what version of the game you have, but on mt phone it looks quite similar to the current version (with 12px arc). I think, but I might be completely off the mark, that it is because that in the original game the tiles are much smaller and therefore 3px is enough to look sleek. Either way, while I like the way it looks right now (after the change) I'm completely open to change it. We can even try to figure out a complete different look - but that's a matter to deal with after we are finished with the functionality. I was just playing a bit with the css to see hoe it works... 
What say you, @Yeedle?

**Comment by yeedle** [comment]
@modicohen I was comparing it to the original game posted on the developer's github. See link in opening post. I agree that it's definitely a matter that can wait for later.

**Comment by modicohen** [comment]
After reviewing the original [code](https://gabrielecirulli.github.io/2048/style/main.css), I see that it is more squared than the android implementation I have on my phone - which is more rounded. Either way it's an easy change that can be done whenever...

**Comment by modicohen** [comment]
I believed this issue is resolved. The board looks fantastic!
What say you, @Yeedle?

**Comment by yeedle** [comment]
@modicohen I concur.
